### ISSUE TITLE
Is this code obsolete

### ISSUE THREAD

**Issue by StratOman** [cinqmarsmedia/The-Devils-Calculator-A-Math-Puzzle-Game#25]
Is there a newer version of this code as ionic V3 is long gone and conversion to V6 is problematic.
Thanks
John

**Comment by ccj242** [comment]
We have no plans to update the codebase to v6 at this time, we did do a performance test against v5 to see if it would be worth updating the codebase at that time but found the benefits pretty negligible. We're actually finishing up a few projects right now still with v3 and it's really not as bad as you might think, though all our newly started projects are v6.

**Comment by StratOman** [comment]
Many thanks.
I did try to update by creating a new V6 using ionic start , then migrated all the components and manged to removed all errors from V code , but too many errors on the build due to incompatible modules. Shame as it's a superb game.
Best John

**Comment by ccj242** [comment]
Thanks John, that's very kind and means a lot. Let me know if I can help with anything!
